#This need loop for all require namespace
{{- range $namespaces_prefix := $.Values.ns_prefix}}
{{- range $namespaces_base := $.Values.ns_base }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ggv-role-edit-binding-developer2
  namespace: {{ $namespaces_prefix }}-{{ $namespaces_base }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ggv-role-edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: k8s-developer2@gogotech.hk
  namespace: {{ $namespaces_prefix }}-{{ $namespaces_base }}
---
 {{- end }}
{{- end }}