#This is Cluster Role only need create once
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ggv-clusternamespace-reader
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  verbs:
  - "get"
  - "list"
  - "watch"
