{{- range $team_namespace_env_mapping := $.Values.ggv_team_namespace_env_mapping_rolebindings }}
{{- range $namespaces_prefix := $team_namespace_env_mapping.ns_prefix }}
{{- range $namespaces_base := $.Values.ns_base }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $team_namespace_env_mapping.group_name }}-{{ $team_namespace_env_mapping.role_name }}-binding-{{ $namespaces_prefix }}-{{ $namespaces_base }}
  namespace: {{ $namespaces_prefix }}-{{ $namespaces_base }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $team_namespace_env_mapping.role_name }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $team_namespace_env_mapping.email }}
  namespace: {{ $namespaces_prefix }}-{{ $namespaces_base }}
---
{{- end }}
{{- end }}
{{- end }}