#This is Cluster Role Binding only need create once, but loop in subjects
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ggv-clusternamespace-reader-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ggv-clusternamespace-reader
subjects:
  {{- range $namespaces := $.Values.namespace_reader_groups}}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $namespaces }}
  namespace: kube-system
  {{- end}}
