
{{- range $crb := $.Values.crb}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $crb.rolebinding }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ $crb.subject_name }}
  namespace: {{ $crb.subject_namespace }}
---
{{- end }}
